.\" Copyright (c) 2005 Rudy Godoy
.TH PIMIXER "1" "June 2005" "xfce4-mixer 0.1" "User Commands"
.SH NAME
pimixer \- a volume control application for the Raspberry Pi desktop
.SH SYNOPSIS
.B pimixer
.SH DESCRIPTION
.PP
pimixer is a fork of xfce4-mixer volume control application for the
Raspberry Pi desktop environment. This software package contains only the
standalone mixer application. You should be able to run it from the menu
system.
.SH COPYRIGHT
Copyright \(co 2005 Rudy Godoy
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

